### ISSUE TITLE
analyze results

### ISSUE THREAD

**Issue by eliseuegewarth** [deeplearningunb/covid-cxr-test#5]

**Comment by eliseuegewarth** [comment]
https://stackoverflow.com/questions/50920908/get-confusion-matrix-from-a-keras-multiclass-model

**Comment by egewarth** [comment]
https://stackoverflow.com/questions/54492862/keras-scikit-learn-python-binary-classification-confusion-matrix-i-may-have

**Comment by eliseuegewarth** [comment]
https://stackoverflow.com/questions/50825936/confusion-matrix-on-images-in-cnn-keras
